### ISSUE TITLE
Vireo deployment plan

### ISSUE THREAD

**Issue by bess** [pulibrary/rdss-catchall#19]
We will need to fork a copy of vireo 4, make local changes, and deploy that version of the application

- [x] Fork vireo in a private repo
- [x] Decide on and document a process for compiling and deploying a package from github

Legacy forked version: https://github.com/PrincetonUniversityLibrary/thesiscentral-vireo/

Current forked version: https://github.com/PrincetonUniversityLibrary/pul-vireo/

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/pull/2573 ensures that the NGINX Plus configuration sets the proper HTTP headers for WebSockets.
